macsec: update operstate when lower device changes
Aquantia/linux-4.14-atlantic-forwarding pull request #7
Opened 2019-11-29 20:28 UTC by mstarovo

Like all other virtual devices (macvlan, vlan), the operstate of a
macsec device should match the state of its lower device. This is done
by calling netif_stacked_transfer_operstate from its netdevice notifier.

We also need to call netif_stacked_transfer_operstate when a new macsec
device is created, so that its operstate is set properly. This is only
relevant when we try to bring the device up directly when we create it.

Radu Rendec proposed a similar patch, inspired from the 802.1q driver,
that included changing the administrative state of the macsec device,
instead of just the operstate. This version is similar to what the
macvlan driver does, and updates only the operstate.

Fixes: c09440f7dcb3 ("macsec: introduce IEEE 802.1AE driver")
Reported-by: Radu Rendec <radu.rendec@gmail.com>
Reported-by: Patrick Talbert <ptalbert@redhat.com>
Signed-off-by: Sabrina Dubroca <sd@queasysnail.net>
Signed-off-by: David S. Miller <davem@davemloft.net>

2019-11-29 20:32 UTC, mstarovo commented
Cherry picking yet another commit from upstream.

This one fixes a couple of things, which were bothering me for some time, e.g.:
1) "state UNKNOWN" was a common thing:
```
$ ip a show macsec0
5: macsec0@enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1468 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 00:17:b6:00:01:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/20 scope global macsec0
       valid_lft forever preferred_lft forever
```
2) previous one could have been fixed by doing an additional `ip link set macsec0 down ; ip link set macsec0 up`, but then it would not react to lower layer (enp1s0) being down:
```
$ sudo ifconfig enp1s0 down
$ ip a show macsec0
5: macsec0@enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1468 qdisc noqueue state UP group default qlen 1000
    link/ether 00:17:b6:00:01:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/20 scope global macsec0
       valid_lft forever preferred_lft forever
```

2019-11-29 20:35 UTC, mstarovo commented
Testing done to verify the changes:
```
mark@spb-lin01:~$ sudo ip addr add 10.0.0.1/27 dev enp1s0; sudo ip link set enp1s0 up
mark@spb-lin01:~$ sudo ip link add link enp1s0 macsec0 type macsec encrypt on && sudo ip link set macsec0 address 00:17:b6:00:01:01 && sudo ip macsec add macsec0 tx sa 0 pn 1 on key 00 12345678901234567890123456789012 && sudo ip macsec add macsec0 rx port 1 address 00:17:b6:00:01:ff && sudo ip macsec add macsec0 rx port 1 address 00:17:b6:00:01:ff sa 0 pn 1 on key 00 00000000000000000000000000000000 && sudo ip macsec add macsec0 rx port 1 address 00:17:b6:00:01:02 && sudo ip macsec add macsec0 rx port 1 address 00:17:b6:00:01:02 sa 0 pn 1 on key 00 01234567890123456789012345678901 && sudo ip addr add 172.16.0.1/20 dev macsec0; sudo ip link set macsec0 up
mark@spb-lin01:~$ ip a show macsec0
4: macsec0@enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1468 qdisc noqueue state UP group default qlen 1000
    link/ether 00:17:b6:00:01:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/20 scope global macsec0
       valid_lft forever preferred_lft forever
mark@spb-lin01:~$ sudo ip link set macsec0 down
mark@spb-lin01:~$ ip a show macsec0
4: macsec0@enp1s0: <BROADCAST,MULTICAST> mtu 1468 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:17:b6:00:01:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/20 scope global macsec0
       valid_lft forever preferred_lft forever
mark@spb-lin01:~$ sudo ip link set macsec0 up
mark@spb-lin01:~$ ip a show macsec0
4: macsec0@enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1468 qdisc noqueue state UP group default qlen 1000
    link/ether 00:17:b6:00:01:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/20 scope global macsec0
       valid_lft forever preferred_lft forever
mark@spb-lin01:~$ sudo ip link set enp1s0 down
mark@spb-lin01:~$ ip a show macsec0
4: macsec0@enp1s0: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1468 qdisc noqueue state LOWERLAYERDOWN group default qlen 1000
    link/ether 00:17:b6:00:01:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/20 scope global macsec0
       valid_lft forever preferred_lft forever
mark@spb-lin01:~$ sudo ip link set enp1s0 up
mark@spb-lin01:~$ ip a show macsec0
4: macsec0@enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1468 qdisc noqueue state UP group default qlen 1000
    link/ether 00:17:b6:00:01:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/20 scope global macsec0
       valid_lft forever preferred_lft forever
```

2019-12-02 09:35 UTC, cail requested changes
Mark, I see only a single commit, but you say you cherrypicked two?
Forgot to push?

Please also put an original commit hash into each of the commit messages, like here:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/macsec.c?h=v4.19.87&id=f5bdad7106fc509f27a627a94671ef2dd7136021

2019-12-02 10:23 UTC, mstarovo commented
@cail Cherry-picked a single commit only.

2019-12-02 11:01 UTC, cail approved these changes

2019-12-02 11:32 UTC, logost approved these changes

2019-12-03 14:51 UTC, merged